#!/bin/busybox sh

root_mount="/mnt/root"

# Functions
rescue_shell() {
	[ -n "$@" ] && echo "ERROR: $@" 1>&2
	echo "Something went wrong. Dropping you to a shell." 1>&2
	exec /bin/sh
}
move_mount() {
	if ! mount --move "$@" "$root_mount/$@"; then
		umount "$@"
		return 1
	fi
}

# Install busybox symlinks
/bin/busybox --install -s

# Mount /sys /proc /dev
mount -t sysfs none /sys || rescue_shell "Failed to mount /sys"
mount -t proc none /proc || rescue_shell "Failed to mount /proc"
mount -t devtmpfs none /dev || rescue_shell "Failed to mount /dev"

# Assemble mdadm arrays
[ -x /sbin/mdadm ] && /sbin/mdadm --assemble --scan

rescue_present=0
root_device=""
init_binary=""

# Process the command line
for arg in $(cat /proc/cmdline); do
	case "$arg" in
		rescue)
			rescue_present=1
		;;
		root=*)
			root_device="${arg#*=}"
			device="$(findfs "$root_device" 2>/dev/null)"
			if [ $? -eq 0 ]; then
				root_device="$device"
			fi
		;;
		init=*)
			init_binary="${arg#*=}"
		;;
	esac
done

[ -e "$root_device" ] || rescue_shell "Root device does not exist: $root_device"
mount -o ro "$root_device" "$root_mount" || rescue_shell "Failed to mount root: $root_device" 
move_mount /sys || rescue_shell "Failed to relocate /sys mount."
move_mount /proc || rescue_shell "Failed to relocate /proc mount."
move_mount /dev || rescue_shell "Failed to relocate /dev mount."

[ $rescue_present -eq 0 ] || rescue_shell "Rescue shell requested."
exec switch_root "$root_mount" "${init_binary:=/sbin/init}"

# vi:set ft=sh:
